In [19]:
# 4726개 데이터 가져오기
import pandas as pd
df_final_tone11 = pd.read_excel('./ESG기사.xlsx')

c:\Users\PC1\AppData\Local\Programs\Python\Python38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
import pandas as pd
df_final_tone11 = pd.read_csv('./new_data_label_all2.csv')

In [2]:
df_final_tone11['특성추출(가중치순 상위 50개)']=df_final_tone11['특성추출(가중치순 상위 50개)'].str.upper()

In [3]:
df_final_tone11=df_final_tone11.replace(" ","")

In [4]:
df_final_tone11.to_csv('./newdata_ESG기사2.csv')

In [5]:
df_final_tone11.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', '제목', '특성추출(가중치순 상위 50개)', '본문',
       '특성추출_번역', 'label', 'score', 'label.1', 'score.1', 'label.2',
       'score.2'],
      dtype='object')

In [35]:
a = pd.read_csv('./fintone/finbert_Tone1.csv',encoding='UTF-8')
b = pd.read_csv('./fintone/finbert_Tone2.csv',encoding='UTF-8')
c = pd.concat([b,a],axis=0)
c.drop(['Unnamed: 0.1', 'Unnamed: 0', '제목', '본문', '본문_번역'], axis=1 , inplace=True)
c = c.reset_index(drop = True)
c

                                       특성추출(가중치순 상위 50개)     label     score
0      노사정,민주노총,중집,한국노총,코로나19,노동계,위원회,원포인트,완전체,합의안,고용...   Neutral  0.982828
1      대림그룹,건설사,대림건설,삼호,고려개발,건설시장,환경변화,합병회사,계열사,첫발,빙하...  Positive  0.999867
2       연료전지,삼성중공업,블룸에너지,온실가스,배출량,공동개발,독일,노르웨이,스리달,캘리포니아   Neutral  0.999954
3      사업주,민주당,개정안,계약갱신청구권,임대차,보장법,근로자,특고,한국경제연구원,6개,...   Neutral  0.999794
4      부회장,반도체,사업장,불안감,코로나19,삼성,신격호,삼성인력개발원,롯데그룹,협력사,...   Neutral  0.982648
...                                                  ...       ...       ...
24506  제조업,코로나19,서비스업,순환변동치,체감경기,bsi,주요국,esi,소매판매,지원금...  Positive  0.999955
24507  연료전지,삼성중공업,블룸에너지,기념행사,온실가스,미국,정호현,노르웨이,스리달,본부장...   Neutral  0.996634
24508  스타트업,인슈어테크,보험금,손보업계,활동데이터,손보사,일자리,손보업,ai,김용덕,코...   Neutral  0.997954
24509  대림건설,건설사,경쟁력,삼호,대림그룹,고려개발,지속성장,빙하기,조남창,영업익,계열사...  Positive  0.647018
24510  위원장,시베리아,반기문,기후악당,호주,다소비,탈원전,환경학,조너선,지구온난화,간담회...  Negative  0.898206

[24511 rows x 3 columns]

In [36]:
e = pd.read_excel('./ESG기사.xlsx')
e.drop(['뉴스 식별자', '일자', '언론사', '기고자', '제목', '통합 분류1', '통합 분류2', '통합 분류3',
       '사건/사고 분류1', '사건/사고 분류2', '사건/사고 분류3', '인물', '위치', '기관', '키워드','URL', '분석제외 여부' ],axis = 1 , inplace=True)
e

c:\Users\PC1\AppData\Local\Programs\Python\Python38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,특성추출(가중치순 상위 50개),본문
0,"경쟁자,김정태,변곡점,신년사,경쟁력,사회가치,인재채용,금융업,빅테크,이자이익,업무영...","[헤럴드경제=서정은 기자] 김정태 하나금융그룹 회장이 ‘플랫폼 금융’, ‘글로벌 금..."
1,"사모펀드,협회장,코로나19,위원장,투자자,금융위,김광수,소비자,빅테크,빅데이터,신년...",은성수 금융위원장과 윤석헌 금융감독원장이 한 해를 뜨겁게 달궜던 잇단 사모펀드 사태...
2,"신년사,금융그룹,기업문화,만큼,esg,김정태,경쟁력,계량화,금융업,비재무적,경쟁자,...",김정태(사진) 하나금융그룹 회장이 “지금 우리에게는 ‘변화의 쓰나미’가 몰려오고 있...
3,"금융그룹,esg,쓰나미,변곡,신년사,변곡점,아시아,사회가치,김정태,업권,경쟁자,기업...",[머니투데이 양성희 기자] \n김정태 하나금융그룹 회장이 내년 경영 키워드로 '플랫...
4,"코로나,신용보증기금,이사장,생텍쥐페리,경쟁력,스타트업,임직원,뉴딜,공공기관,80조,...",[머니투데이 김세관 기자] 윤대희 신용보증기금 이사장이 코로나19(COVID-19)...
...,...,...
4756,"코베스트로,독일,esg,신기술,이산화탄소,유럽,배출량,화석연료,프랑크,폴리,생산공장...","[머니투데이 레버쿠젠(독일)=유영호 기자] [편집자주] ESG(환경, 사회적책임, ..."
4757,"한국,보고서,세계은행,투자자,연구원,에크나스,5위,전문가,기업환경,기업환경보고서,2...","[머니투데이 황국상 기자] [편집자주] ESG(환경, 사회적책임, 지배구조)에 대한..."
4758,"iss,한국,shareholder,timing,투자자,지배구조,워렌,주주총회,esg...","[머니투데이 황국상 기자] [편집자주] ESG(환경, 사회적책임, 지배구조)에 대한..."
4759,"소비자,친환경,온라인,아이스팩,소비자들,생협,esg,재활용,최우식,포장상자,물류센터...","[머니투데이 김지성 기자, 정인지 기자] [편집자주] ESG(환경, 사회적책임, 지..."
4760,"신기술,사퇴서,응시료,상승장,美中,오프라인,승전보,넥쏘,주담대,1억,탈북민,뛰자,시...",[머니투데이 이원광 기자] [종합]\n힘빠진 성장경제 ESG로 다시 뛰자\n‘탄소제...

In [37]:
d = pd.read_csv('./fintone/df_final_tone_4761.csv')
d.drop(['Unnamed: 0.1', 'Unnamed: 0', '일자',  '본문_번역'], axis=1 , inplace=True)
d

                                                     본문     label     score
0     [헤럴드경제=서정은 기자] 김정태 하나금융그룹 회장이 ‘플랫폼 금융’, ‘글로벌 금...   Neutral  0.970925
1     은성수 금융위원장과 윤석헌 금융감독원장이 한 해를 뜨겁게 달궜던 잇단 사모펀드 사태...   Neutral  0.613521
2     김정태(사진) 하나금융그룹 회장이 “지금 우리에게는 ‘변화의 쓰나미’가 몰려오고 있...  Negative  0.953513
3     [머니투데이 양성희 기자] \n김정태 하나금융그룹 회장이 내년 경영 키워드로 '플랫...   Neutral  0.999736
4     [머니투데이 김세관 기자] 윤대희 신용보증기금 이사장이 코로나19(COVID-19)...  Positive  0.999973
...                                                 ...       ...       ...
4756  [머니투데이 레버쿠젠(독일)=유영호 기자] [편집자주] ESG(환경, 사회적책임, ...  Positive  0.611812
4757  [머니투데이 황국상 기자] [편집자주] ESG(환경, 사회적책임, 지배구조)에 대한...   Neutral  0.793176
4758  [머니투데이 황국상 기자] [편집자주] ESG(환경, 사회적책임, 지배구조)에 대한...   Neutral  0.793176
4759  [머니투데이 김지성 기자, 정인지 기자] [편집자주] ESG(환경, 사회적책임, 지...   Neutral  0.728972
4760  [머니투데이 이원광 기자] [종합]\n힘빠진 성장경제 ESG로 다시 뛰자\n‘탄소제...  Positive  0.998023

[4761 rows x 3 columns]

In [38]:
new_a=pd.concat([e, d] , axis=1)
new_a.drop('본문', axis=1, inplace=True)
new_a.isna().sum()

특성추출(가중치순 상위 50개)    0
label                0
score                0
dtype: int64

In [41]:
total = pd.concat([c, new_a], axis=0)
total = total.reset_index(drop = True)
total.drop('특성추출(가중치순 상위 50개)', axis=1, inplace=True)
total

          label     score
0       Neutral  0.982828
1      Positive  0.999867
2       Neutral  0.999954
3       Neutral  0.999794
4       Neutral  0.982648
...         ...       ...
29267  Positive  0.611812
29268   Neutral  0.793176
29269   Neutral  0.793176
29270   Neutral  0.728972
29271  Positive  0.998023

[29272 rows x 2 columns]

In [42]:
import pandas as pd
df_final_tone11 = pd.read_csv('./new_data_label_all2.csv')
data = df_final_tone11[['특성추출(가중치순 상위 50개)','label', 'score', 'label.1', 'score.1', 'label.2', 'score.2']].reset_index(drop = True)
data.drop(['label.2','score.2'],axis=1 , inplace=True)
data

,특성추출(가중치순 상위 50개),label,score,label.1,score.1
0,"노사정,민주노총,중집,한국노총,코로나19,노동계,위원회,원포인트,완전체,합의안,고용...",Social,0.947515,Social,0.917265
1,"대림그룹,건설사,대림건설,삼호,고려개발,건설시장,환경변화,합병회사,계열사,첫발,빙하...",Social,0.483581,Environmental,0.910894
2,"연료전지,삼성중공업,블룸에너지,온실가스,배출량,공동개발,독일,노르웨이,스리달,캘리포니아",Environmental,0.992858,Environmental,0.982949
3,"사업주,민주당,개정안,계약갱신청구권,임대차,보장법,근로자,특고,한국경제연구원,6개,...",Social,0.982398,Governance,0.855661
4,"부회장,반도체,사업장,불안감,코로나19,삼성,신격호,삼성인력개발원,롯데그룹,협력사,...",Social,0.946831,Social,0.593323
...,...,...,...,...,...
29267,"코베스트로,독일,esg,신기술,이산화탄소,유럽,배출량,화석연료,프랑크,폴리,생산공장...",Environmental,0.992582,Environmental,0.987966
29268,"한국,보고서,세계은행,투자자,연구원,에크나스,5위,전문가,기업환경,기업환경보고서,2...",Social,0.876937,Social,0.907024
29269,"iss,한국,shareholder,timing,투자자,지배구조,워렌,주주총회,esg...",Governance,0.874962,Governance,0.991710
29270,"소비자,친환경,온라인,아이스팩,소비자들,생협,esg,재활용,최우식,포장상자,물류센터...",Environmental,0.933597,Environmental,0.713665
29271,"신기술,사퇴서,응시료,상승장,美中,오프라인,승전보,넥쏘,주담대,1억,탈북민,뛰자,시...",Social,0.921543,Social,0.987712

In [47]:
total.columns = total.columns.str.replace('label','label.2')
total.columns = total.columns.str.replace('score','score.2')

data = pd.concat([data, total], axis=1)
data

,특성추출(가중치순 상위 50개),label,score,label.1,score.1,label.2,score.2
0,"노사정,민주노총,중집,한국노총,코로나19,노동계,위원회,원포인트,완전체,합의안,고용...",Social,0.947515,Social,0.917265,Neutral,0.982828
1,"대림그룹,건설사,대림건설,삼호,고려개발,건설시장,환경변화,합병회사,계열사,첫발,빙하...",Social,0.483581,Environmental,0.910894,Positive,0.999867
2,"연료전지,삼성중공업,블룸에너지,온실가스,배출량,공동개발,독일,노르웨이,스리달,캘리포니아",Environmental,0.992858,Environmental,0.982949,Neutral,0.999954
3,"사업주,민주당,개정안,계약갱신청구권,임대차,보장법,근로자,특고,한국경제연구원,6개,...",Social,0.982398,Governance,0.855661,Neutral,0.999794
4,"부회장,반도체,사업장,불안감,코로나19,삼성,신격호,삼성인력개발원,롯데그룹,협력사,...",Social,0.946831,Social,0.593323,Neutral,0.982648
...,...,...,...,...,...,...,...
29267,"코베스트로,독일,esg,신기술,이산화탄소,유럽,배출량,화석연료,프랑크,폴리,생산공장...",Environmental,0.992582,Environmental,0.987966,Positive,0.611812
29268,"한국,보고서,세계은행,투자자,연구원,에크나스,5위,전문가,기업환경,기업환경보고서,2...",Social,0.876937,Social,0.907024,Neutral,0.793176
29269,"iss,한국,shareholder,timing,투자자,지배구조,워렌,주주총회,esg...",Governance,0.874962,Governance,0.991710,Neutral,0.793176
29270,"소비자,친환경,온라인,아이스팩,소비자들,생협,esg,재활용,최우식,포장상자,물류센터...",Environmental,0.933597,Environmental,0.713665,Neutral,0.728972
29271,"신기술,사퇴서,응시료,상승장,美中,오프라인,승전보,넥쏘,주담대,1억,탈북민,뛰자,시...",Social,0.921543,Social,0.987712,Positive,0.998023

In [51]:
data['특성추출(가중치순 상위 50개)']=data['특성추출(가중치순 상위 50개)'].str.upper()

In [52]:
data=data.replace(" ","")

In [53]:
data.to_csv('./newdata_ESG기사3.csv')

In [54]:
# 특성추출에서 기업 추출
from tqdm import tqdm
import pandas as pd

df_final_tone11 = pd.read_csv('./newdata_ESG기사3.csv')
# df_final_tone21 = pd.read_csv('./df_final_tone21.csv')
# df_final_tone = pd.concat([df_final_tone11,df_final_tone21])

data = df_final_tone11[['특성추출(가중치순 상위 50개)','label', 'score', 'label.1', 'score.1', 'label.2', 'score.2']].reset_index(drop = True)

# 기업명 가져오기
ESGlist = pd.read_csv('./ESGlist.csv', encoding='cp949')
stock_list = ESGlist['기업명'].to_list()

# 제목에서 종목명 추출

data['종목명'] = 'default'
data_mt = []    # multiple title

for sl in tqdm(stock_list) :
    for i in range(len(data)) :
        if sl in data.loc[i, '특성추출(가중치순 상위 50개)'].split(',') :       # 특성추출에 종목명이 있을 때(대문자로 통일)
            if data.loc[i, '종목명'] == 'default' :    # 종목명이 하나인 경우
                data.loc[i, '종목명'] = sl             # 종목명 부여
                data_d = data.loc[i]
                data_mt.append(data_d)
            else :                                     # 종목명이 여러개인 경우
                row_tmp = data.loc[i]                  # 행 복사
                row_tmp['종목명'] = sl                 # 종목명 부여
                data_mt.append(row_tmp)
data_mt = pd.DataFrame(data_mt)
data_mt

  0%|          | 4/950 [00:01<04:28,  3.53it/s]C:\Users\PC1\AppData\Local\Temp\ipykernel_12024\1695440077.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row_tmp['종목명'] = sl                 # 종목명 부여
100%|██████████| 950/950 [07:02<00:00,  2.25it/s]

,특성추출(가중치순 상위 50개),label,score,label.1,score.1,label.2,score.2,종목명
13972,"AJ,자회사,계열사,상반기,종합렌탈사,주차장,렌터카,익스포저,코로나바이러스,중고차,...",None,0.960147,None,0.984420,Neutral,0.999999,AJ네트웍스
3636,"제주항공,대표이사,애경유화,애경그룹,애경화학,이석주,애경산업,부사장,AK홀딩스,김이...",Social,0.911340,Social,0.899802,Neutral,0.999729,AK홀딩스
3700,"제주항공,애경유화,애경그룹,이석주,애경화학,부사장,애경산업,아시아나항공,AK,사장단...",Social,0.725317,None,0.913293,Neutral,0.999792,AK홀딩스
3708,"애경유화,제주항공,애경그룹,이석주,애경화학,부사장,김이배,사장단,상반기,애경산업,A...",Social,0.506517,None,0.964317,Neutral,0.999911,AK홀딩스
3716,"애경유화,제주항공,대표이사,애경화학,애경산업,애경그룹,부사장,인사안,사장단,이석주,...",Social,0.543245,None,0.936076,Neutral,0.999878,AK홀딩스
...,...,...,...,...,...,...,...,...
5103,"정산애강,계열사,건설경기,매출액,000호,태광실업,황광식,만큼,배관재,휴켐스,생산성...",Social,0.973323,None,0.666551,Neutral,0.999890,휴켐스
13628,"봉사활동,임직원,흥국화재,삼성화재,사회공헌비용,당기순이익,보험사,순이익,사회공헌,하...",Environmental,0.586617,Social,0.979567,Neutral,0.645122,흥국화재
25468,"봉사활동,임직원,흥국화재,삼성화재,사회공헌비용,당기순이익,보험사,순이익,사회공헌,하...",Environmental,0.586617,Social,0.979567,Neutral,0.990127,흥국화재
28437,"서스틴베스트,ESG,상반기,상장기업,신한지주,흥국화재,삼성바이오로직스,사외이사,AA...",Governance,0.479563,Governance,0.990084,Neutral,0.593073,흥국화재
16779,"피케이밸브,경쟁력,흥아해운,STX,LNG,STX컨소시엄,OWNER,제품군,보통주,신...",Social,0.883686,None,0.752603,Neutral,0.558204,흥아해운

13673

In [7]:
data_mt

,특성추출(가중치순 상위 50개),label,score,label.1,score.1,label.2,score.2,종목명
13972,"AJ,자회사,계열사,상반기,종합렌탈사,주차장,렌터카,익스포저,코로나바이러스,중고차,...",None,0.960147,None,0.984420,Neutral,0.596775,AJ네트웍스
3636,"제주항공,대표이사,애경유화,애경그룹,애경화학,이석주,애경산업,부사장,AK홀딩스,김이...",Social,0.911340,Social,0.899802,Neutral,0.794822,AK홀딩스
3700,"제주항공,애경유화,애경그룹,이석주,애경화학,부사장,애경산업,아시아나항공,AK,사장단...",Social,0.725317,None,0.913293,Neutral,0.757892,AK홀딩스
3708,"애경유화,제주항공,애경그룹,이석주,애경화학,부사장,김이배,사장단,상반기,애경산업,A...",Social,0.506517,None,0.964317,Neutral,0.808157,AK홀딩스
3716,"애경유화,제주항공,대표이사,애경화학,애경산업,애경그룹,부사장,인사안,사장단,이석주,...",Social,0.543245,None,0.936076,Neutral,0.806900,AK홀딩스
...,...,...,...,...,...,...,...,...
5103,"정산애강,계열사,건설경기,매출액,000호,태광실업,황광식,만큼,배관재,휴켐스,생산성...",Social,0.973323,None,0.666551,Positive,0.886965,휴켐스
13628,"봉사활동,임직원,흥국화재,삼성화재,사회공헌비용,당기순이익,보험사,순이익,사회공헌,하...",Environmental,0.586617,Social,0.979567,Neutral,0.695723,흥국화재
25468,"봉사활동,임직원,흥국화재,삼성화재,사회공헌비용,당기순이익,보험사,순이익,사회공헌,하...",Environmental,0.586617,Social,0.979567,Neutral,0.695723,흥국화재
28437,"서스틴베스트,ESG,상반기,상장기업,신한지주,흥국화재,삼성바이오로직스,사외이사,AA...",Governance,0.479563,Governance,0.990084,Positive,0.670433,흥국화재
16779,"피케이밸브,경쟁력,흥아해운,STX,LNG,STX컨소시엄,OWNER,제품군,보통주,신...",Social,0.883686,None,0.752603,Positive,0.758688,흥아해운

In [55]:
data_mt.to_csv('./newdata_ESG기사_기업3.csv')

In [2]:
data_mt.groupby('종목명').count().max()

특성추출(가중치순 상위 50개)    123
dtype: int64

In [10]:
# 중복 행 제거

data_mt = data_mt.drop_duplicates(keep='first',ignore_index=True)
# data_mt2 = data_mt2.drop_duplicates(keep='first',ignore_index=True)

In [ ]:
data_mt = data_mt.drop_duplicates(keep='first',ignore_index=True)
data_mt.to_csv('./data_mt.csv')

In [17]:
# 중복 행 삭제된 종목명 붙은 뉴스데이터 추출
data_mt.to_csv('./data_mt.csv')
# data_mt2.to_csv('./data_mt2.csv')